//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CT_DASHBOARDEntities : DbContext
    {
        public CT_DASHBOARDEntities()
            : base("name=CT_DASHBOARDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAO_CAO> BAO_CAO { get; set; }
        public virtual DbSet<BAO_CAO_CHI_TIET> BAO_CAO_CHI_TIET { get; set; }
        public virtual DbSet<CHI_TIEU> CHI_TIEU { get; set; }
        public virtual DbSet<DIA_BAN> DIA_BAN { get; set; }
        public virtual DbSet<DON_VI> DON_VI { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
