//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_VI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_VI()
        {
            this.BAO_CAO = new HashSet<BAO_CAO>();
            this.NGUOI_DUNG = new HashSet<NGUOI_DUNG>();
        }
    
        public int ID { get; set; }
        public string MA_DON_VI { get; set; }
        public string TEN_DON_VI { get; set; }
        public Nullable<int> VI_TRI { get; set; }
        public string TRANG_THAI { get; set; }
        public Nullable<bool> QUAN_TRONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAO_CAO> BAO_CAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOI_DUNG> NGUOI_DUNG { get; set; }
    }
}
