//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO_CHI_TIET
    {
        public int ID { get; set; }
        public Nullable<int> BAO_CAO { get; set; }
        public string DIA_BAN { get; set; }
        public string CHI_TIEU { get; set; }
        public Nullable<double> THUC_HIEN_TRONG_KY { get; set; }
        public Nullable<double> THUC_HIEN { get; set; }
        public Nullable<double> KE_HOACH { get; set; }
        public Nullable<double> CUNG_KY { get; set; }
        public string DVT { get; set; }
        public Nullable<int> NGUOI_TAO { get; set; }
        public Nullable<int> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string DIEN_GIAI { get; set; }
    
        public virtual BAO_CAO BAO_CAO1 { get; set; }
        public virtual CHI_TIEU CHI_TIEU1 { get; set; }
        public virtual DIA_BAN DIA_BAN1 { get; set; }
    }
}
