//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAO_CAO()
        {
            this.BAO_CAO_CHI_TIET = new HashSet<BAO_CAO_CHI_TIET>();
        }
    
        public int ID { get; set; }
        public string TEN_BC { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string DON_VI { get; set; }
        public Nullable<bool> IS_LATEST { get; set; }
        public string TRANG_THAI { get; set; }
        public string DIEN_GIAI { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<int> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_DUYET { get; set; }
        public Nullable<int> NGUOI_DUYET { get; set; }
        public string TRANG_THAI_DUYET { get; set; }
        public string LY_DO_TU_CHOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAO_CAO_CHI_TIET> BAO_CAO_CHI_TIET { get; set; }
        public virtual DON_VI DON_VI1 { get; set; }
    }
}
