//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHI_TIEU()
        {
            this.BAO_CAO_CHI_TIET = new HashSet<BAO_CAO_CHI_TIET>();
        }
    
        public int ID { get; set; }
        public string MA_CHI_TIEU { get; set; }
        public string TEN_CHI_TIEU { get; set; }
        public string TEN_DAY_DU { get; set; }
        public string MA_MAU { get; set; }
        public string PARENTID { get; set; }
        public string DON_VI { get; set; }
        public string DVT { get; set; }
        public Nullable<byte> VI_TRI { get; set; }
        public string TRANG_THAI { get; set; }
        public Nullable<bool> QUAN_TRONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAO_CAO_CHI_TIET> BAO_CAO_CHI_TIET { get; set; }
    }
}
