//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_DUNG
    {
        public int ID { get; set; }
        public string HO_TEN { get; set; }
        public string DIEN_THOAI { get; set; }
        public string EMAIL { get; set; }
        public string DON_VI { get; set; }
        public string TRANG_THAI { get; set; }
        public string VAI_TRO { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> NGUOI_TAO { get; set; }
        public Nullable<int> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
    
        public virtual DON_VI DON_VI1 { get; set; }
    }
}
